# frontend/nginx.conf
server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Tenta encontrar o arquivo, se não encontrar, redireciona para o index.html
        try_files $uri $uri/ /index.html;
    }

    # Cache opcional para arquivos estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        log_not_found off;
    }
}
